### PR TITLE
add new product API completed

### PR DESCRIPTION
**Pull request by United-Programmers**
Now the user can add new products inside the database

### CODE REVIEW

**Comment by chadrackkyungu** [comment]
Great job with no conflict

**Comment by United-Programmers** [comment]
I fogot to add something

**Comment by chadrackkyungu** [comment]
What is it ?

**Comment by United-Programmers** [comment]
It's something small i don't even know how to explain it

**Comment by chadrackkyungu** [comment]
alright you can explain it next time than

**Comment by United-Programmers** [comment]
ok cool

**Comment by chadrackkyungu** [comment]
cool

**Review by chadrackkyungu — APPROVED** [review]

**Pull request merged**
